name: mobile automation
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
 
jobs:
  build:
    runs-on: macos-12
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
 
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://registry.npmjs.org/
 
    - name: Clean install dependencies
      run: |
        npm install
 
    - name: Set up Appium
      run: |
        npm install -g appium
        appium -v
        appium &>/dev/null &
 
    # - name: Install Appium drivers
    #   run: |
    #     appium driver install uiautomator2
    #     appium driver install xcuitest
 
    - name: Print Node.js version
      run: node -v
 
    - name: Print ADB devices
      run: adb devices
 
    - name: Run Appium Android tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: |
          adb devices
          npm run mobile
